'use client';
import { useState } from 'react';
import type { Scrap } from '../notes';
export type ContributionType = 'question' | 'thought' | 'beginning';
const PROMPTS = {
  question: { label: 'A QUESTION', heading: 'What are you still wondering?', placeholder: 'Why do we...' },
  thought: { label: 'A THOUGHT', heading: 'What followed you here?', placeholder: 'I keep thinking about...' },
  beginning: { label: 'A BEGINNING', heading: 'Begin something you will not finish.', placeholder: 'The morning after...' },
} as const;
export default function FragmentReader({ scrap, onClose, onContributionSubmit }: { scrap: Scrap | null; onClose: () => void; onContributionSubmit: (value: string, type: ContributionType) => void }) {
  const [flipped,setFlipped]=useState(false); const [type,setType]=useState<ContributionType>('question'); const [text,setText]=useState(''); const [folding,setFolding]=useState(false);
  if (!scrap) return null;
  const close=()=>{setFlipped(false);setText('');setType('question');setFolding(false);onClose();};
  if (scrap.kind==='question') { const p=PROMPTS[type]; return <div className="fragment-reader-shell"><button className="fragment-reader-backdrop" onClick={close} aria-label="Close"/><article className={`empty-page-reader ${folding?'is-folding':''}`}><button className="reader-x" onClick={close}>×</button><span className="empty-page-index">AN EMPTY PAGE / FOR YOU</span><p className="empty-page-preface">There are enough finished thoughts here.</p><h2>Leave something<br/><em>unfinished.</em></h2><div className="contribution-types">{(['question','thought','beginning'] as ContributionType[]).map(t=><button key={t} className={type===t?'is-selected':''} onClick={()=>setType(t)}>{PROMPTS[t].label}</button>)}</div><div className="contribution-prompt">{p.heading}</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={p.placeholder} maxLength={280} autoFocus/><div className="empty-page-footer"><span>{text.length} / 280</span><button disabled={!text.trim()||folding} onClick={()=>{if(!text.trim())return;setFolding(true);window.setTimeout(()=>{onContributionSubmit(text.trim(),type);setText('');setFolding(false);},950)}}>{folding?'FOLDING...':'LEAVE IT HERE →'}</button></div><span className="page-fold fold-one"/><span className="page-fold fold-two"/></article></div> }
  if (scrap.kind==='polaroid') return <div className="fragment-reader-shell"><button className="fragment-reader-backdrop" onClick={close} aria-label="Close"/><article className="memory-reader"><button className="reader-x" onClick={close}>×</button><button className={`memory-polaroid ${flipped?'is-flipped':''}`} onClick={()=>setFlipped(v=>!v)}><span className="memory-polaroid-inner"><span className="memory-front"><span className="memory-image" style={{backgroundImage:scrap.imageUrl?`url(${scrap.imageUrl})`:undefined}}/><span className="memory-caption">{scrap.caption||'untitled'}</span></span><span className="memory-back">{scrap.backText||'nothing was written on the back.'}</span></span></button><div className="memory-copy"><span>MEMORY / FOUND OBJECT</span><h2>{scrap.caption||scrap.title||'Untitled'}</h2><p>Click the photograph to turn it over.</p></div></article></div>;
  return <div className="fragment-reader-shell"><button className="fragment-reader-backdrop" onClick={close} aria-label="Close"/><article className="document-reader"><button className="reader-x" onClick={close}>×</button><div className="document-spine"/><span className="document-status">{scrap.kind.toUpperCase()} / UNFINISHED</span>{scrap.title&&<h2>{scrap.title}</h2>}<div className="document-rule"/><div className="document-copy">{scrap.fullText||scrap.body||'Nothing else was written.'}</div><footer><span>NO CONCLUSION FOUND</span><span>ARCHIVE / NEXUS</span></footer></article></div>;
}
